---
output:
  html_document: 
    toc: true
    toc_float: true
---


<link rel="stylesheet" href="styles.css" type="text/css">


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<p align="center">
*Curriculum Vitae*
</p>


<p align="center">
<font size="+2">**Mariem Bouhadda **</font>
</p>
----

<p align="justify">
**Status:** An engineering Student at the <a href='http://www.essai.rnu.tn/accueil.htm'> Higher School of Statistics and Information Analysis</a>

**Skills:** <a href='https://www.r-project.org'>`R` Software</a>, `Python`, Data Visualization, Machine Learning 


</p>



<!-- ---- -->

<!-- <p align="justify"> -->
<!-- **Summary** Dhafer Malouche obtained a PhD in Statistics and Applied Mathematics from <a href='http://www.univ-tlse3.fr'>Paul Sabatier University</a> in Toulouse, France in October 1997. In September 1998, he obtained an Assistant Professor position at the <a href='http://www.uc.rnu.tn'>University of Sousse</a> in Tunisia. During the 2002-2003 academic year, he was a visiting professor <a href='http://www.yorku.ca/index.html'>York University</a> in Toronto. In 2003, he returned to Tunisia and served as Assistant Professor at the new Engineering School of Statistics in Tunisia, called the  <a href='http://www.essai.rnu.tn/accueil.htm'>Higher School of Statistics and Information Analysis</a>, becoming an Associate Professor in 2011 and Professor in 2018. He is now teaching several courses on Data Analysis (Bayesian Statistics, Data Mining, Regression Models, Times Series, Big Data, advanced `R`). He is supervising numerous projects and doctorate dissertations pertaining to real cases across various topics and has developed many collaborative, multidisciplinary research programs. In 2011, he was a Fulbright Scholar at the Department of Statistics at <a href='https://statistics.stanford.edu'>Stanford University</a>. Since 2012, he has worked with political science scholars on the democratic transition in Tunisia. He has implemented three national surveys in Tunisia about the political transition and local governance (November 2012, June 2014 and March 2015). In 2014-2015, he worked in the <a href='http://gld.gu.se'>Governance Local Development Program</a> of <a href='https://www.gu.se/english'>Gothenburg University</a>. He was invited to join the <a href='https://macmillan.yale.edu'>MacMillan Center</a> at <a href='http://www.yale.edu'>Yale University</a> as a visiting professor. In 2016-2017, Dhafer served as a Fulbright Visiting Scholar at the <a href='https://www.isr.umich.edu/cps/'>Center for Political Studies</a> of the  <a href='http://home.isr.umich.edu'>Institute for Social Research</a> at the <a href='http://umich.edu'>University of Michigan</a>. -->
<!-- </p> -->

<!-- ---- -->



## Education

<p align="justify">

**2016-2019: <a href='http://www.essai.rnu.tn/accueil.htm'> Higher School of Statistics and Information Analysis</a>**


<p align="justify">

Main focus on a 3 axis curriculum: 

* Theoretical and Applied Statistics

* Computer Science

* Economics and Finance



**2014 - 2016: <a href='http://www.ipeit.rnu.tn/fr/content/presentation-de-lipeit'> Preparatory Institute for Engineering Studies of Tunis</a>**

* Mathematical Physics (MP).

**2011 - 2014  : <a href=''> Ibn Kholdoun High School</a>**

* Bachelor’s Degree in Mathematics : With highest honour




## Internships

<p align="justify">

**July 2018 - August 2018:  Engineering Intern at OpenWay**


<p align="justify">

Building a Web app in R that scrapes Tunisian trade
data based on user’s input.


**June 2017 -August 2017: Summer Intern at One To One for research and Polling**

* Developing data entry Applications using CSPro.
* Cleaning and analyzing data using SPSS and Excel.



## Projects


<p align="justify">

**Machine Learning project: Credit Risk Classification**

<p align="justify">

Creating a Shiny Web application that visualizes:

* Univariate and Bivariate Analysis
* Compares different classification models in terms of accuracy and
ROC curves.


**Stock Market Modeling and Forecasting**

<p align="justify">


* Studying the ARCH and GARCH models from a theoretical and practical
point.
* Applying forecasting models to predict the variance of CAC 40 stock
indices.
* Comparing the forecasts using multiple statistical tests.


**Certifications**

* Training course of : Self development - Public speaking skills -
intelligent communication
* Voltaire Certificate: Measures the mastery level of writing difficulties
in the French language. (Business Level)
* First Aid certificate from the Tunisian Red Crescent : LEVEL 1









## Contact 

>  *email:*  <maryem.bouhadda@gmail.com> \
>  *website:* <a href='https://bouhadda.github.io'>https://bouhadda.github.io</a>

